# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 05:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/recommend_picture/%Y/%m/%d')),
                ('pubdate', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='classes',
            name='student',
        ),
        migrations.AddField(
            model_name='procedure',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 14, 5, 29, 49, 127386, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 14, 5, 29, 56, 100962, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='recommend',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childrenrecipe.Recipe'),
        ),
    ]
