# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, upload_to='exhibited_picture/%Y/%m/%d'),
        ),
    ]
