# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0002_auto_20161013_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='introduce',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
