# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0002_auto_20160921_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='measureunits',
            new_name='portion',
        ),
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
    ]
