# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0002_auto_20160914_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('md5', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/upload/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Image'),
        ),
    ]
