# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0003_auto_20160916_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(upload_to='images/exhibited_picture/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='image',
            field=models.ImageField(default=1, upload_to='images/exhibited_picture/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
