# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0004_auto_20160917_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/exhibited_picture/%Y/%m/%d'),
        ),
    ]
