# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0005_auto_20161013_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='browse',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
