# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0005_auto_20160918_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/procedure_picture/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='image',
            field=models.ImageField(upload_to='images/recommend_picture/%Y/%m/%d'),
        ),
    ]
