# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0005_category_is_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_tag',
            field=models.IntegerField(),
        ),
    ]
