# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0006_auto_20160918_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='image',
            field=models.ImageField(upload_to='recommend_picture/%Y/%m/%d'),
        ),
    ]
