# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0007_auto_20160920_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tips',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, upload_to='procedure_picture/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='exihibitpic',
            field=models.ImageField(upload_to='exhibited_picture/%Y/%m/%d'),
        ),
    ]
