# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=11)),
                ('sax', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='student',
            field=models.ManyToManyField(to='polls.Student'),
        ),
    ]
